name: youfit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  provider: ^6.0.2
  http: ^0.13.4
  image_picker: ^0.8.2
  flutter_spinkit: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
provider: ^6.0.2
http: ^0.13.4
flutter:
  uses-material-design: true
  assets:
    - img/
  fonts:
    - family: Abel-Regular
      fonts:
        - asset: fonts/Abel-Regular.ttf
    - family : Rock3D-Regular
      fonts:
        - asset: fonts/Rock3D-Regular.ttf
    - family : Quicksand-VariableFont_wght
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf